# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "44091e3136d321ff1c6d20fc11743ef7"
name = "mk-fe-mdb-connector"
handle = "mk-fe-mdb-connector"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
